/*
 * This file was autogenerated by OSQP-Python on August 11, 2020 at 18:10:20.
 * 
 * This file contains the workspace variables needed by OSQP.
 */

#include "types.h"
#include "qdldl_interface.h"

// Define data structure
c_int Pdata_i[10] = {
0,
0,
1,
0,
1,
2,
0,
1,
2,
3,
};
c_int Pdata_p[5] = {
0,
1,
3,
6,
10,
};
c_float Pdata_x[10] = {
(c_float)1.00000000000000000000,
(c_float)1.00000000000000000000,
(c_float)1.00000000000000000000,
(c_float)1.00000000000000000000,
(c_float)1.00000000000000000000,
(c_float)1.00000000000000000000,
(c_float)1.00000000000000000000,
(c_float)1.00000000000000000000,
(c_float)1.00000000000000000000,
(c_float)1.00000000000000000000,
};
csc Pdata = {10, 4, 4, Pdata_p, Pdata_i, Pdata_x, -1};
c_int Adata_i[16] = {
0,
1,
2,
3,
0,
1,
2,
3,
0,
1,
2,
3,
0,
1,
2,
3,
};
c_int Adata_p[5] = {
0,
4,
8,
12,
16,
};
c_float Adata_x[16] = {
(c_float)1.00000000000000000000,
(c_float)1.00000000000000000000,
(c_float)1.00000000000000000000,
(c_float)1.00000000000000000000,
(c_float)1.00000000000000000000,
(c_float)1.00000000000000000000,
(c_float)1.00000000000000000000,
(c_float)1.00000000000000000000,
(c_float)1.00000000000000000000,
(c_float)1.00000000000000000000,
(c_float)1.00000000000000000000,
(c_float)1.00000000000000000000,
(c_float)1.00000000000000000000,
(c_float)1.00000000000000000000,
(c_float)1.00000000000000000000,
(c_float)1.00000000000000000000,
};
csc Adata = {16, 4, 4, Adata_p, Adata_i, Adata_x, -1};
c_float qdata[4] = {
(c_float)0.00000000000000000000,
(c_float)0.00000000000000000000,
(c_float)0.00000000000000000000,
(c_float)0.00000000000000000000,
};
c_float ldata[4] = {
(c_float)-1000000000000000019884624838656.00000000000000000000,
(c_float)-1000000000000000019884624838656.00000000000000000000,
(c_float)-1000000000000000019884624838656.00000000000000000000,
(c_float)-1000000000000000019884624838656.00000000000000000000,
};
c_float udata[4] = {
(c_float)1000000000000000019884624838656.00000000000000000000,
(c_float)1000000000000000019884624838656.00000000000000000000,
(c_float)1000000000000000019884624838656.00000000000000000000,
(c_float)1000000000000000019884624838656.00000000000000000000,
};
OSQPData data = {4, 4, &Pdata, &Adata, qdata, ldata, udata};

// Define settings structure
OSQPSettings settings = {(c_float)0.10000000000000000555, (c_float)0.00000100000000000000, 10, 1, 0, (c_float)5.00000000000000000000, 4000, (c_float)0.00010000000000000000, (c_float)0.00010000000000000000, (c_float)0.00010000000000000000, (c_float)0.00010000000000000000, (c_float)1.60000000000000008882, (enum linsys_solver_type) LINSYS_SOLVER, 0, 25, 1, };

// Define scaling structure
c_float Dscaling[4] = {
(c_float)1.00000000000000000000,
(c_float)1.00000000000000000000,
(c_float)1.00000000000000000000,
(c_float)1.00000000000000000000,
};
c_float Dinvscaling[4] = {
(c_float)1.00000000000000000000,
(c_float)1.00000000000000000000,
(c_float)1.00000000000000000000,
(c_float)1.00000000000000000000,
};
c_float Escaling[4] = {
(c_float)1.00000000000000000000,
(c_float)1.00000000000000000000,
(c_float)1.00000000000000000000,
(c_float)1.00000000000000000000,
};
c_float Einvscaling[4] = {
(c_float)1.00000000000000000000,
(c_float)1.00000000000000000000,
(c_float)1.00000000000000000000,
(c_float)1.00000000000000000000,
};
OSQPScaling scaling = {(c_float)1.00000000000000000000, Dscaling, Escaling, (c_float)1.00000000000000000000, Dinvscaling, Einvscaling};

// Define linsys_solver structure
c_int linsys_solver_L_i[25] = {
1,
2,
3,
7,
2,
3,
4,
5,
6,
7,
3,
4,
5,
6,
7,
4,
5,
6,
7,
5,
6,
7,
6,
7,
7,
};
c_int linsys_solver_L_p[9] = {
0,
4,
10,
15,
19,
22,
24,
25,
25,
};
c_float linsys_solver_L_x[25] = {
(c_float)-0.00000100000000000000,
(c_float)-0.00000100000000000000,
(c_float)-0.00000100000000000000,
(c_float)-0.00000100000000000000,
(c_float)0.99999900000200014905,
(c_float)0.99999900000200014905,
(c_float)0.99999800000400018707,
(c_float)0.99999800000400018707,
(c_float)0.99999800000400018707,
(c_float)0.99999900000200014905,
(c_float)0.49999974997764984330,
(c_float)0.49999924998846062563,
(c_float)0.49999924998846062563,
(c_float)0.49999924998846062563,
(c_float)0.49999974997764984330,
(c_float)0.33333288888608858525,
(c_float)0.33333288888608858525,
(c_float)0.33333288888608858525,
(c_float)0.33333322221227029702,
(c_float)0.00000099999766667211,
(c_float)0.00000099999766667211,
(c_float)-0.00000000000033333256,
(c_float)0.00000099999666667778,
(c_float)-0.00000000000033333222,
(c_float)-0.00000000000033333189,
};
csc linsys_solver_L = {25, 8, 8, linsys_solver_L_p, linsys_solver_L_i, linsys_solver_L_x, -1};
c_float linsys_solver_Dinv[8] = {
(c_float)-0.00000100000000000000,
(c_float)0.99999800000400018707,
(c_float)500000.25006348354509100318,
(c_float)666666.77784257417079061270,
(c_float)-0.00000099999900000233,
(c_float)-0.00000099999900000333,
(c_float)-0.00000099999900000433,
(c_float)750000.06256711552850902081,
};
c_int linsys_solver_P[8] = {
7,
0,
1,
2,
4,
5,
6,
3,
};
c_float linsys_solver_bp[8];
c_float linsys_solver_sol[8];
c_float linsys_solver_rho_inv_vec[4] = {
(c_float)1000000.00000000000000000000,
(c_float)1000000.00000000000000000000,
(c_float)1000000.00000000000000000000,
(c_float)1000000.00000000000000000000,
};
c_int linsys_solver_Pdiag_idx[4] = {
0,
2,
5,
9,
};
c_int linsys_solver_KKT_i[30] = {
0,
1,
0,
1,
2,
0,
1,
2,
3,
0,
1,
2,
3,
4,
1,
2,
3,
5,
1,
2,
3,
6,
1,
2,
3,
7,
4,
5,
6,
0,
};
c_int linsys_solver_KKT_p[9] = {
0,
1,
3,
6,
10,
14,
18,
22,
30,
};
c_float linsys_solver_KKT_x[30] = {
(c_float)-1000000.00000000000000000000,
(c_float)1.00000099999999991773,
(c_float)1.00000000000000000000,
(c_float)1.00000000000000000000,
(c_float)1.00000099999999991773,
(c_float)1.00000000000000000000,
(c_float)1.00000000000000000000,
(c_float)1.00000000000000000000,
(c_float)1.00000099999999991773,
(c_float)1.00000000000000000000,
(c_float)1.00000000000000000000,
(c_float)1.00000000000000000000,
(c_float)1.00000000000000000000,
(c_float)-1000000.00000000000000000000,
(c_float)1.00000000000000000000,
(c_float)1.00000000000000000000,
(c_float)1.00000000000000000000,
(c_float)-1000000.00000000000000000000,
(c_float)1.00000000000000000000,
(c_float)1.00000000000000000000,
(c_float)1.00000000000000000000,
(c_float)-1000000.00000000000000000000,
(c_float)1.00000000000000000000,
(c_float)1.00000000000000000000,
(c_float)1.00000000000000000000,
(c_float)1.00000099999999991773,
(c_float)1.00000000000000000000,
(c_float)1.00000000000000000000,
(c_float)1.00000000000000000000,
(c_float)1.00000000000000000000,
};
csc linsys_solver_KKT = {30, 8, 8, linsys_solver_KKT_p, linsys_solver_KKT_i, linsys_solver_KKT_x, -1};
c_int linsys_solver_PtoKKT[10] = {
1,
3,
4,
6,
7,
8,
22,
23,
24,
25,
};
c_int linsys_solver_AtoKKT[16] = {
10,
14,
18,
2,
11,
15,
19,
5,
12,
16,
20,
9,
26,
27,
28,
29,
};
c_int linsys_solver_rhotoKKT[4] = {
13,
17,
21,
0,
};
QDLDL_float linsys_solver_D[8] = {
-1000000,
1,
0,
0,
-1000000,
-1000000,
-1000000,
0,
};
QDLDL_int linsys_solver_etree[8] = {
1,
2,
3,
4,
5,
6,
7,
-1,
};
QDLDL_int linsys_solver_Lnz[8] = {
4,
6,
5,
4,
3,
2,
1,
0,
};
QDLDL_int   linsys_solver_iwork[24];
QDLDL_bool  linsys_solver_bwork[8];
QDLDL_float linsys_solver_fwork[8];
qdldl_solver linsys_solver = {QDLDL_SOLVER, &solve_linsys_qdldl, &update_linsys_solver_matrices_qdldl, &update_linsys_solver_rho_vec_qdldl, &linsys_solver_L, linsys_solver_Dinv, linsys_solver_P, linsys_solver_bp, linsys_solver_sol, linsys_solver_rho_inv_vec, (c_float)0.00000100000000000000, 4, 4, linsys_solver_Pdiag_idx, 4, &linsys_solver_KKT, linsys_solver_PtoKKT, linsys_solver_AtoKKT, linsys_solver_rhotoKKT, linsys_solver_D, linsys_solver_etree, linsys_solver_Lnz, linsys_solver_iwork, linsys_solver_bwork, linsys_solver_fwork, };

// Define solution
c_float xsolution[4];
c_float ysolution[4];

OSQPSolution solution = {xsolution, ysolution};

// Define info
OSQPInfo info = {0, "Unsolved", OSQP_UNSOLVED, 0.0, 0.0, 0.0};

// Define workspace
c_float work_rho_vec[4] = {
(c_float)0.00000100000000000000,
(c_float)0.00000100000000000000,
(c_float)0.00000100000000000000,
(c_float)0.00000100000000000000,
};
c_float work_rho_inv_vec[4] = {
(c_float)1000000.00000000000000000000,
(c_float)1000000.00000000000000000000,
(c_float)1000000.00000000000000000000,
(c_float)1000000.00000000000000000000,
};
c_int work_constr_type[4] = {
-1,
-1,
-1,
-1,
};
c_float work_x[4];
c_float work_y[4];
c_float work_z[4];
c_float work_xz_tilde[8];
c_float work_x_prev[4];
c_float work_z_prev[4];
c_float work_Ax[4];
c_float work_Px[4];
c_float work_Aty[4];
c_float work_delta_y[4];
c_float work_Atdelta_y[4];
c_float work_delta_x[4];
c_float work_Pdelta_x[4];
c_float work_Adelta_x[4];
c_float work_D_temp[4];
c_float work_D_temp_A[4];
c_float work_E_temp[4];

OSQPWorkspace workspace = {
&data, (LinSysSolver *)&linsys_solver,
work_rho_vec, work_rho_inv_vec,
work_constr_type,
work_x, work_y, work_z, work_xz_tilde,
work_x_prev, work_z_prev,
work_Ax, work_Px, work_Aty,
work_delta_y, work_Atdelta_y,
work_delta_x, work_Pdelta_x, work_Adelta_x,
work_D_temp, work_D_temp_A, work_E_temp,
&settings, &scaling, &solution, &info};

