<?xml version="1.0"?>
<!-- 
Units: m, kg
Author: Avik De 
-->

<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="sdab">

	<!-- Define parameters -->
	<xacro:property name="pi" value="3.14159265359"/>
	<xacro:property name="wbody" value="3"/>
	<xacro:property name="lbody" value="12"/>
	<!-- vertical offset of wing attachment point from COM -->
	<xacro:property name="d" value="4"/>
	<!-- inertial properties -->
	<xacro:property name="mb" value="100"/>
	<xacro:property name="ixx" value="3333"/>
	<xacro:property name="iyy" value="3333"/>
	<xacro:property name="izz" value="1000"/>
	<!-- See the mathematica file for how these were tuned to approximately match Jafferis (2016) -->
	<xacro:property name="cbar" value="4"/>
	<xacro:property name="dspar" value="0.5"/>
	<!-- radial wing length *without the wing root offset*. Lw=Rwing+Rwingoffset -->
	<!-- radial distance from center to start of wing -->
	<xacro:property name="RwingOffset" value="3"/>
	<xacro:property name="Rwing" value="14"/>
	<xacro:property name="tmem" value="0.0015"/>
	<xacro:property name="sparInertial">
		<mass value="0.72"/>
		<inertia ixx="0.03" ixy="0" ixz="0" iyy="11.775" iyz="0" izz="11.775" />
	</xacro:property>
	<xacro:property name="memInertial">
		<mass value="0.06"/>
		<inertia ixx="0.08" ixy="0.0" ixz="0.0" iyy="1.06" iyz="0.0" izz="0.981" />
	</xacro:property>
	<!-- Stiffness and damping properties -->
	<xacro:property name="khinge" value="3"/>
	<xacro:property name="bhinge" value="2"/>
	<xacro:property name="kstroke" value="65"/> <!-- total act = 240/T^2 + 30 -->
	
	<!-- Define materials -->
	<material name="Black1">
		<color rgba="0 0 0 1.0"/>
	</material>
	<material name="Red1">
		<color rgba="1.0 0 0 1.0"/>
	</material>
	<material name="Gray1">
		<color rgba="0 0 0 0.3"/>
	</material>
	<material name="Blue1">
		<color rgba="0 0 1 1.0"/>
	</material>
	
	<!-- Body -->
	<link name="body">
		<visual>
			<origin xyz="0 0 0.0" rpy="0 0 0"/>
			<geometry>
				<box size="${wbody} ${wbody} ${lbody}"/>
			</geometry>
			<material name="Blue1"/>
		 </visual>
		<inertial>
			<mass value="${mb}"/>
			<inertia ixx="${ixx}" ixy="0.0" ixz="0.0" iyy="${iyy}" iyz="0.0" izz="${izz}"/>
		</inertial>
	</link>

	<!-- Define our wing macro -->
	<xacro:macro name="wing" params="sign prefix sparcol">
		<!--In robobee literature, "Ixx" = spanwise inertia, "Izz" = chordwise inertia. So, the wing frame has x along spar, z up, y pointing out of the wing plane. The first rpy below orients the frame so it is as expected.-->
		<link name="${prefix}wing_spar">
			<visual>
				<origin xyz="0 ${sign*(0.5*Rwing)} 0.0" rpy="0 0 ${sign*0.5*pi}"/>
				<geometry>
					<box size="${Rwing} ${dspar} ${dspar}"/>
				</geometry>
				<material name="${sparcol}"/>
			</visual>
		<inertial>
			<xacro:insert_block name="sparInertial" />
		</inertial>
		<!-- pybullet does not expose spring_stiffness but does expose these so add them here too. We are not expecting contact -->
		<contact>
			<stiffness value="${kstroke}"/>
			<damping value="0"/>
		</contact>
		</link>

		<link name="${prefix}wing_membrane">
			<visual>
				<origin xyz="0 ${sign*(0.5*Rwing)} ${-0.5 * cbar}" rpy="0 0 ${sign*0.5*pi}"/>
				<geometry>
					<box size="${Rwing} ${tmem} ${cbar}"/>
				</geometry>
				<material name="Gray1"/>
			</visual>
		<inertial>
			<xacro:insert_block name="memInertial" />
		</inertial>
		<!-- pybullet does not expose spring_stiffness but does expose these so add them here too. We are not expecting contact -->
		<contact>
			<stiffness value="${khinge}"/>
			<damping value="${bhinge}"/>
		</contact>
		</link>
	
		<!-- * * * Joint Definitions * * * -->
	
		<joint name="${prefix}wing_stroke" type="continuous">
			<parent link="body"/>
			<child link="${prefix}wing_spar"/>
			<axis xyz="0 0 ${sign}"/>
			<origin xyz="0.0 ${sign*RwingOffset} ${d}" rpy="0 0 0"/>
			<!-- <dynamics damping="${dampingSpar}" friction="0.0" spring_stiffness="${stiffnessSpar}" spring_reference="0"/> -->
		</joint>
	
		<joint name="${prefix}wing_hinge" type="continuous">
			<parent link="${prefix}wing_spar"/>
			<child link="${prefix}wing_membrane"/>
			<axis xyz="0 ${sign} 0"/>
			<origin xyz="0.0 0 0.0" rpy="0 0 0"/>
			<!-- <dynamics damping="${dampingHinge}" friction="0.0" spring_stiffness="${stiffnessHinge}" spring_reference="0"/> -->
		</joint>

	</xacro:macro>

	<!-- Two wings -->
	<xacro:wing sign="1" prefix="l" sparcol="Black1"/>
	<xacro:wing sign="-1" prefix="r" sparcol="Red1"/>
</robot>
