<?xml version="1.0"?>
<!-- 
Units: m, kg
Author: Avik De 
-->

<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="sdab">

	<!-- Define parameters -->
	<xacro:property name="pi" value="3.14159265359"/>
	<xacro:property name="wbody" value="3"/>
	<xacro:property name="lbody" value="12"/>
	<!-- radial distance from center to start of wing -->
	<xacro:property name="RwingOffset" value="4"/>
	<!-- diameter of spar -->
	<xacro:property name="dspar" value="1"/>
	<!-- radial wing length -->
	<xacro:property name="Rwing" value="12"/>
	<!-- mean chord length -->
	<xacro:property name="cbar" value="5"/>
	<!-- vertical offset of wing attachment point from COM -->
	<xacro:property name="d" value="2"/>
	<!-- inertial properties -->
	<xacro:property name="mb" value="100"/>
	<xacro:property name="ixx" value="3333"/>
	<xacro:property name="iyy" value="3333"/>
	<xacro:property name="izz" value="1000"/>
	<xacro:property name="mwing" value="0.55"/>
	<!-- Stiffness and damping properties -->
	<xacro:property name="whinge" value="2.5"/>
	<xacro:property name="kstroke" value="65"/> <!-- total act = 240/T^2 + 30 -->
	
	<!-- Define materials -->
	<material name="Black1">
		<color rgba="0 0 0 1.0"/>
	</material>
	<material name="Red1">
		<color rgba="1.0 0 0 1.0"/>
	</material>
	<material name="Gray1">
		<color rgba="0 0 0 0.3"/>
	</material>
	<material name="Blue1">
		<color rgba="0 0 1 1.0"/>
	</material>
	
	<!-- Body -->
	<link name="body">
		<visual>
			<origin xyz="0 0 0.0" rpy="0 0 0"/>
			<geometry>
				<box size="${wbody} ${wbody} ${lbody}"/>
			</geometry>
			<material name="Blue1"/>
		 </visual>
		<inertial>
			<mass value="${mb}"/>
			<inertia ixx="${ixx}" ixy="0.0" ixz="0.0" iyy="${iyy}" iyz="0.0" izz="${izz}"/>
		</inertial>
	</link>

	<!-- Define our wing macro -->
	<xacro:macro name="wing" params="sign prefix sparcol">

		<link name="${prefix}wing_spar">
			<visual>
				<origin xyz="0 ${sign * 0.5 * (Rwing + RwingOffset)} 0.0" rpy="0 0 0"/>
				<geometry>
					<box size="${dspar} ${RwingOffset + Rwing} ${dspar}"/>
				</geometry>
				<material name="${sparcol}"/>
			</visual>
		<inertial>
			<mass value="0"/>
			<inertia ixx="0" ixy="0.0" ixz="0.0" iyy="0" iyz="0.0" izz="0"/>
		</inertial>
		<!-- pybullet does not expose spring_stiffness but does expose these so add them here too. We are not expecting contact -->
		<contact>
			<stiffness value="${kstroke}"/>
			<damping value="0"/>
		</contact>
		</link>

		<link name="${prefix}wing_membrane">
			<visual>
				<origin xyz="0 ${sign * 0.5 * (Rwing + RwingOffset)} ${-0.5 * cbar}" rpy="0 0 0"/>
				<geometry>
					<box size="${dspar} ${Rwing} ${cbar}"/>
				</geometry>
				<material name="Gray1"/>
			</visual>
		<inertial>
			<mass value="${mwing}"/>
			<inertia ixx="${1.0/12.0 * mwing * (Rwing*Rwing + cbar*cbar)}" ixy="0.0" ixz="0.0" iyy="${1.0/12.0 * mwing * (dspar*dspar + cbar*cbar)}" iyz="0.0" izz="${1.0/12.0 * mwing * (dspar*dspar + Rwing*Rwing)}"/>
		</inertial>
		<!-- pybullet does not expose spring_stiffness but does expose these so add them here too. We are not expecting contact -->
		<contact>
			<stiffness value="${3*whinge}"/>
			<damping value="${1.8*whinge}"/>
		</contact>
		</link>
	
		<!-- * * * Joint Definitions * * * -->
	
		<joint name="${prefix}wing_stroke" type="continuous">
			<parent link="body"/>
			<child link="${prefix}wing_spar"/>
			<axis xyz="0 0 ${-1 * sign}"/>
			<origin xyz="0.0 0 ${d}" rpy="0 0 0"/>
			<!-- <dynamics damping="${dampingSpar}" friction="0.0" spring_stiffness="${stiffnessSpar}" spring_reference="0"/> -->
		</joint>
	
		<joint name="${prefix}wing_hinge" type="continuous">
			<parent link="${prefix}wing_spar"/>
			<child link="${prefix}wing_membrane"/>
			<axis xyz="0 1 0"/>
			<origin xyz="0.0 0 0.0" rpy="0 0 0"/>
			<!-- <dynamics damping="${dampingHinge}" friction="0.0" spring_stiffness="${stiffnessHinge}" spring_reference="0"/> -->
		</joint>

	</xacro:macro>

	<!-- Two wings -->
	<xacro:wing sign="-1" prefix="l" sparcol="Black1"/>
	<xacro:wing sign="1" prefix="r" sparcol="Red1"/>
</robot>
