<?xml version="1.0"?>
<!-- 
Units: m, kg
Author: Avik De 
-->

<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="sdab">

	<!-- Define parameters -->
	<xacro:property name="pi" value="3.14159265359"/>
	<xacro:property name="wbody" value="0.003"/>
	<xacro:property name="lbody" value="0.012"/>
	<!-- radial distance from center to start of wing -->
	<xacro:property name="RwingOffset" value="0.004"/>
	<!-- diameter of spar -->
	<xacro:property name="dspar" value="0.001"/>
	<!-- radial wing length -->
	<xacro:property name="Rwing" value="0.012"/>
	<!-- mean chord length -->
	<xacro:property name="cbar" value="0.005"/>
	<!-- vertical offset of wing attachment point from COM -->
	<xacro:property name="d" value="0.002"/>
	<!-- inertial properties -->
	<xacro:property name="mb" value="80e-6"/>
	<xacro:property name="mspar" value="1e-6"/>
	<xacro:property name="mwing" value="1e-6"/>
	<!-- Stiffness and damping properties -->
	<xacro:property name="stiffnessHinge" value="2e-2"/>
	<xacro:property name="dampingHinge" value="1e-2"/>
	<xacro:property name="stiffnessSpar" value="4e-5"/>
	<xacro:property name="dampingSpar" value="7e-8"/>
	
	<!-- Define materials -->
	<material name="Black1">
		<color rgba="0 0 0 1.0"/>
	</material>
	<material name="Red1">
		<color rgba="1.0 0 0 1.0"/>
	</material>
	<material name="Gray1">
		<color rgba="0 0 0 0.3"/>
	</material>
	<material name="Blue1">
		<color rgba="0 0 1 1.0"/>
	</material>
	
	<!-- Body -->
	<link name="body">
		<visual>
			<origin xyz="0 0 0.0" rpy="0 0 0"/>
			<geometry>
				<box size="${wbody} ${wbody} ${lbody}"/>
			</geometry>
			<material name="Blue1"/>
		 </visual>
		<inertial>
			<mass value="${mb}"/>
			<inertia ixx="${10.0*1.0/12.0 * mb * (lbody*lbody + wbody*wbody)}" ixy="0.0" ixz="0.0" iyy="${10.0*1.0/12.0 * mb * (lbody*lbody + wbody*wbody)}" iyz="0.0" izz="${10.0*1.0/12.0 * mb * (wbody*wbody + wbody*wbody)}"/>
		</inertial>
	</link>

	<!-- Define our wing macro -->
	<xacro:macro name="wing" params="sign prefix sparcol">

		<link name="${prefix}wing_spar">
			<visual>
				<origin xyz="0 ${sign * 0.5 * (Rwing + RwingOffset)} 0.0" rpy="0 0 0"/>
				<geometry>
					<box size="${dspar} ${RwingOffset + Rwing} ${dspar}"/>
				</geometry>
				<material name="${sparcol}"/>
			</visual>
		<inertial>
			<mass value="${mspar}"/>
			<inertia ixx="${1.0/12.0 * mspar * ((Rwing+RwingOffset)*(Rwing+RwingOffset) + dspar*dspar)}" ixy="0.0" ixz="0.0" iyy="${1.0/12.0 * mspar * (2 * (Rwing+RwingOffset)*(Rwing+RwingOffset))}" iyz="0.0" izz="${1.0/12.0 * mspar * ((Rwing+RwingOffset)*(Rwing+RwingOffset) + dspar*dspar)}"/>
		</inertial>
		<!-- pybullet does not expose spring_stiffness but does expose these so add them here too. We are not expecting contact -->
		<contact>
			<stiffness value="${stiffnessSpar}"/>
			<damping value="${dampingSpar}"/>
		</contact>
		</link>

		<link name="${prefix}wing_membrane">
			<visual>
				<origin xyz="0 ${sign * 0.5 * (Rwing + RwingOffset)} ${-0.5 * cbar}" rpy="0 0 0"/>
				<geometry>
					<box size="${dspar} ${Rwing} ${cbar}"/>
				</geometry>
				<material name="Gray1"/>
			</visual>
		<inertial>
			<mass value="${mwing}"/>
			<inertia ixx="${1.0/12.0 * mwing * (Rwing*Rwing + cbar*cbar)}" ixy="0.0" ixz="0.0" iyy="${1.0/12.0 * mwing * (dspar*dspar + cbar*cbar)}" iyz="0.0" izz="${1.0/12.0 * mwing * (dspar*dspar + Rwing*Rwing)}"/>
		</inertial>
		<!-- pybullet does not expose spring_stiffness but does expose these so add them here too. We are not expecting contact -->
		<contact>
			<stiffness value="${stiffnessHinge}"/>
			<damping value="${dampingHinge}"/>
		</contact>
		</link>
	
		<!-- * * * Joint Definitions * * * -->
	
		<joint name="${prefix}wing_stroke" type="continuous">
			<parent link="body"/>
			<child link="${prefix}wing_spar"/>
			<axis xyz="0 0 ${-1 * sign}"/>
			<origin xyz="0.0 0 ${d}" rpy="0 0 0"/>
			<!-- <dynamics damping="${dampingSpar}" friction="0.0" spring_stiffness="${stiffnessSpar}" spring_reference="0"/> -->
		</joint>
	
		<joint name="${prefix}wing_hinge" type="continuous">
			<parent link="${prefix}wing_spar"/>
			<child link="${prefix}wing_membrane"/>
			<axis xyz="0 1 0"/>
			<origin xyz="0.0 0 0.0" rpy="0 0 0"/>
			<!-- <dynamics damping="${dampingHinge}" friction="0.0" spring_stiffness="${stiffnessHinge}" spring_reference="0"/> -->
		</joint>

	</xacro:macro>

	<!-- Two wings -->
	<xacro:wing sign="-1" prefix="l" sparcol="Black1"/>
	<xacro:wing sign="1" prefix="r" sparcol="Red1"/>
</robot>
