#ifndef WORKSPACE_H
#define WORKSPACE_H

/*
 * This file was autogenerated by OSQP-Python on September 25, 2020 at 19:15:49.
 * 
 * This file contains the prototypes for all the workspace variables needed
 * by OSQP. The actual data is contained inside workspace.c.
 */

#include "types.h"
#include "qdldl_interface.h"

// Data structure prototypes
extern csc Pdata;
extern csc Adata;
extern c_float qdata[18];
extern c_float ldata[12];
extern c_float udata[12];
extern OSQPData data;

// Settings structure prototype
extern OSQPSettings settings;

// Scaling structure prototypes
extern c_float Dscaling[18];
extern c_float Dinvscaling[18];
extern c_float Escaling[12];
extern c_float Einvscaling[12];
extern OSQPScaling scaling;

// Prototypes for linsys_solver structure
extern csc linsys_solver_L;
extern c_float linsys_solver_Dinv[30];
extern c_int linsys_solver_P[30];
extern c_float linsys_solver_bp[30];
extern c_float linsys_solver_sol[30];
extern c_float linsys_solver_rho_inv_vec[12];
extern c_int linsys_solver_Pdiag_idx[4];
extern csc linsys_solver_KKT;
extern c_int linsys_solver_PtoKKT[4];
extern c_int linsys_solver_AtoKKT[30];
extern c_int linsys_solver_rhotoKKT[12];
extern QDLDL_float linsys_solver_D[30];
extern QDLDL_int linsys_solver_etree[30];
extern QDLDL_int linsys_solver_Lnz[30];
extern QDLDL_int   linsys_solver_iwork[90];
extern QDLDL_bool  linsys_solver_bwork[30];
extern QDLDL_float linsys_solver_fwork[30];
extern qdldl_solver linsys_solver;

// Prototypes for solution
extern c_float xsolution[18];
extern c_float ysolution[12];

extern OSQPSolution solution;

// Prototype for info structure
extern OSQPInfo info;

// Prototypes for the workspace
extern c_float work_rho_vec[12];
extern c_float work_rho_inv_vec[12];
extern c_int work_constr_type[12];
extern c_float work_x[18];
extern c_float work_y[12];
extern c_float work_z[12];
extern c_float work_xz_tilde[30];
extern c_float work_x_prev[18];
extern c_float work_z_prev[12];
extern c_float work_Ax[12];
extern c_float work_Px[18];
extern c_float work_Aty[18];
extern c_float work_delta_y[12];
extern c_float work_Atdelta_y[18];
extern c_float work_delta_x[18];
extern c_float work_Pdelta_x[18];
extern c_float work_Adelta_x[12];
extern c_float work_D_temp[18];
extern c_float work_D_temp_A[18];
extern c_float work_E_temp[12];

extern OSQPWorkspace workspace;

#endif // ifndef WORKSPACE_H
