#ifndef WORKSPACE_H
#define WORKSPACE_H

/*
 * This file was autogenerated by OSQP-Python on November 17, 2020 at 19:38:49.
 * 
 * This file contains the prototypes for all the workspace variables needed
 * by OSQP. The actual data is contained inside workspace.c.
 */

#include "types.h"
#include "qdldl_interface.h"

// Data structure prototypes
extern csc Pdata;
extern csc Adata;
extern c_float qdata[45];
extern c_float ldata[39];
extern c_float udata[39];
extern OSQPData data;

// Settings structure prototype
extern OSQPSettings settings;

// Scaling structure prototypes
extern c_float Dscaling[45];
extern c_float Dinvscaling[45];
extern c_float Escaling[39];
extern c_float Einvscaling[39];
extern OSQPScaling scaling;

// Prototypes for linsys_solver structure
extern csc linsys_solver_L;
extern c_float linsys_solver_Dinv[84];
extern c_int linsys_solver_P[84];
extern c_float linsys_solver_bp[84];
extern c_float linsys_solver_sol[84];
extern c_float linsys_solver_rho_inv_vec[39];
extern c_int linsys_solver_Pdiag_idx[45];
extern csc linsys_solver_KKT;
extern c_int linsys_solver_PtoKKT[45];
extern c_int linsys_solver_AtoKKT[111];
extern c_int linsys_solver_rhotoKKT[39];
extern QDLDL_float linsys_solver_D[84];
extern QDLDL_int linsys_solver_etree[84];
extern QDLDL_int linsys_solver_Lnz[84];
extern QDLDL_int   linsys_solver_iwork[252];
extern QDLDL_bool  linsys_solver_bwork[84];
extern QDLDL_float linsys_solver_fwork[84];
extern qdldl_solver linsys_solver;

// Prototypes for solution
extern c_float xsolution[45];
extern c_float ysolution[39];

extern OSQPSolution solution;

// Prototype for info structure
extern OSQPInfo info;

// Prototypes for the workspace
extern c_float work_rho_vec[39];
extern c_float work_rho_inv_vec[39];
extern c_int work_constr_type[39];
extern c_float work_x[45];
extern c_float work_y[39];
extern c_float work_z[39];
extern c_float work_xz_tilde[84];
extern c_float work_x_prev[45];
extern c_float work_z_prev[39];
extern c_float work_Ax[39];
extern c_float work_Px[45];
extern c_float work_Aty[45];
extern c_float work_delta_y[39];
extern c_float work_Atdelta_y[45];
extern c_float work_delta_x[45];
extern c_float work_Pdelta_x[45];
extern c_float work_Adelta_x[39];
extern c_float work_D_temp[45];
extern c_float work_D_temp_A[45];
extern c_float work_E_temp[39];

extern OSQPWorkspace workspace;

#endif // ifndef WORKSPACE_H
