#ifndef WORKSPACE_H
#define WORKSPACE_H

/*
 * This file was autogenerated by OSQP-Python on October 22, 2020 at 19:16:52.
 * 
 * This file contains the prototypes for all the workspace variables needed
 * by OSQP. The actual data is contained inside workspace.c.
 */

#include "types.h"
#include "qdldl_interface.h"

// Data structure prototypes
extern csc Pdata;
extern csc Adata;
extern c_float qdata[49];
extern c_float ldata[43];
extern c_float udata[43];
extern OSQPData data;

// Settings structure prototype
extern OSQPSettings settings;

// Scaling structure prototypes
extern c_float Dscaling[49];
extern c_float Dinvscaling[49];
extern c_float Escaling[43];
extern c_float Einvscaling[43];
extern OSQPScaling scaling;

// Prototypes for linsys_solver structure
extern csc linsys_solver_L;
extern c_float linsys_solver_Dinv[92];
extern c_int linsys_solver_P[92];
extern c_float linsys_solver_bp[92];
extern c_float linsys_solver_sol[92];
extern c_float linsys_solver_rho_inv_vec[43];
extern c_int linsys_solver_Pdiag_idx[49];
extern csc linsys_solver_KKT;
extern c_int linsys_solver_PtoKKT[94];
extern c_int linsys_solver_AtoKKT[115];
extern c_int linsys_solver_rhotoKKT[43];
extern QDLDL_float linsys_solver_D[92];
extern QDLDL_int linsys_solver_etree[92];
extern QDLDL_int linsys_solver_Lnz[92];
extern QDLDL_int   linsys_solver_iwork[276];
extern QDLDL_bool  linsys_solver_bwork[92];
extern QDLDL_float linsys_solver_fwork[92];
extern qdldl_solver linsys_solver;

// Prototypes for solution
extern c_float xsolution[49];
extern c_float ysolution[43];

extern OSQPSolution solution;

// Prototype for info structure
extern OSQPInfo info;

// Prototypes for the workspace
extern c_float work_rho_vec[43];
extern c_float work_rho_inv_vec[43];
extern c_int work_constr_type[43];
extern c_float work_x[49];
extern c_float work_y[43];
extern c_float work_z[43];
extern c_float work_xz_tilde[92];
extern c_float work_x_prev[49];
extern c_float work_z_prev[43];
extern c_float work_Ax[43];
extern c_float work_Px[49];
extern c_float work_Aty[49];
extern c_float work_delta_y[43];
extern c_float work_Atdelta_y[49];
extern c_float work_delta_x[49];
extern c_float work_Pdelta_x[49];
extern c_float work_Adelta_x[43];
extern c_float work_D_temp[49];
extern c_float work_D_temp_A[49];
extern c_float work_E_temp[43];

extern OSQPWorkspace workspace;

#endif // ifndef WORKSPACE_H
